### ISSUE TITLE
TODOs?

### ISSUE THREAD

**Issue by endrebak** [kyleam/snakemake-mode#10]
I am teaching myself elisp, but do not have much stuff to work on right now, so if you make a TODO I'll start looking into it. 

I guess a readme might be in order, but for me to help on that I would need to ask you loads of inane questions about the code.

(Making it easier to debug snakemake code would be awesome, but I do not have any ideas about how that could be done as of now. I wrote those graphing functions and added syntax-highlighting for embedded R for that purpose.)

**Comment by kyleam** [comment]
Hmm, here are the TODOs I have locally:

* Add menus (`easy-menu-define`)

  This should be simple, but I haven't had the motivation because I
  don't use menus.

* Add command to display `snakemake --summary`

  This would probably take some work, and I haven't really thought
  about it much.

* Completions?

* Define `hs-special-modes-alist`

* Snippets 

  See Stan mode snippets and Haskell mode snippets for examples of
  packaging these.

* Navigation commands

  `{beginning,end}-of-defun-function` for rule blocks

  `python-nav-{backward,forward}-block` replacements for rule fields

**Comment by endrebak** [comment]
* Menus

Do not personally use/like them, so would be hard for me to create (and not that interesting to write for the same reasons).

* Summary 

What info do you hope to glean from the summary?

* Completions?

I am getting solid completions, but perhaps it is because I am using spacemacs? Would be neat if `company-mode` (my backend) could suggest snakemake keywords without them being in the buffer in front of point. But this might be hard to improve on for me due to possible spacemacs interactions?

* `hs-special-modes-alist`

Interesting, never heard of it. hideshow seems like a more flexible folding/narrowing mode. Also neat that you can define forward-sexp functions, although I do not understand the one shown for python.

* snippets

Perhaps I'll start here or with `hs-special-modes-alist`. I'll try to read the stan-mode snippets folder for inspiration (`stan` looks awesome, btw). Haskell-mode does not have snippets included afaics. (And `ghc-mod` is so great you do not need them much anyways.)

* Navigation commands

Also a great idea. Can be easier than imenu for just moving one or two blocks up/down.

**Comment by kyleam** [comment]
> * Summary
>
> What info do you hope to glean from the summary?

I'm not sure how to answer that aside from "the information shown by
`snakemake --summary [target ...]`".

> * Completions?  I am getting solid completions, but perhaps it is
>because I am using spacemacs? Would be neat if `company-mode` (my
>backend) could suggest snakemake keywords without them being in the
>buffer in front of point. But this might be hard to improve on for me
>due to possible spacemacs interactions?

I don't know much about spacemacs, so I'm not sure.  In general, I
don't use code completion for any languages, and instead just rely on
hippie-expand and, to a lesser extent, abbrev definitions and
snippets.  Because of this, I really haven't had a motivation to
explore this for Snakemake mode.

> * snippets
>
> Perhaps I'll start here or with `hs-special-modes-alist`. I'll try to
> read the stan-mode snippets folder for inspiration (`stan` looks
> awesome, btw). Haskell-mode does not have snippets included
> afaics. (And `ghc-mod` is so great you do not need them much anyways.)

I may have been thinking of the Haskell snippets at
https://github.com/polypus74/HSnippets when I took the note, but I'm
not sure.  How these are packaged is orthogonal to the actual snippet
contents, so we can put packaging off until we think we have a
collection of snippets worth including.

**Comment by endrebak** [comment]
I have the following snippet for `hs-special-modes-alist`, but it does not work:

```
;;; HideShow

(add-to-list 'hs-special-modes-alist '(snakemake-mode "^rule .*\\>" nil "#" nil
                                                      nil))
```

The regex works if I try it with `re-search` so I am confused about what is wrong.

**Comment by kyleam** [comment]
Closing, as I don't think keeping this open serves any purpose.
