### ISSUE TITLE
What is the snakemake popup actions supposed to do/how are they supposed to work?

### ISSUE THREAD

**Issue by endrebak** [kyleam/snakemake-mode#11]
Whenever I am in a snakefile and try one of the actions I get "no snakefile found for <dirname>`.

I do not really want to run the workflows within emacs, so this does not bother me but I suspect it is undesired behavior.

My file is called `"/Users/labsenter/havpryd/code/programmable_epigenetics/snakefiles/csaw/graph_filter_parameters.snakefile"` if that might matter.

**Comment by kyleam** [comment]
The commands check if there is a file named "Snakefile" in either the
current directory or, if that fails, possibly in another directory,
depending on the value of `snakemake-root-dir-function`.  The
docstrings of `snakemake-root-dir-function` and
`snakemake-snakefile-directory`, as well as the header commentary of
snakemake.el, have more information.

Can you give me more details on your typical setup?  (Even if you
don't want to build targets through `compile`, this same system is
used for the `snakemake-graph`, which is related to #12).  Are
"*.snakefile" files always used as an argument snakemake's `-s`
option, or are they used in a toplevel file named "Snakefile" via
`include:`?  If they're given to the `-s` option, is snakemake usually
called from a different directory?

**Comment by endrebak** [comment]
I have folders upon folders of snakefiles for each of my projects. 

I am usually in the base folder of my current project calling snakefiles in subfolders.

Example of my last invocation:

`endrebak@havpryd ~/c/programmable_epigenetics> snakemake --snakefile snakefiles/csaw/graph_filter_parameters.snakefile -j 4`.

Will read the docs of the functions you mentioned.

**Comment by endrebak** [comment]
It seems your function only finds files called `Snakefile`, right? So no matter what I set the dir functions to it would not work in my case.

My original graph functions just took the absolute path of the file visited by the buffer, which is what I would want in 100% of cases. Perhaps you (or I) could add some similar capability with an interactive function (`snakemake-create-dag(/rulegraph)-for-this-file`)?

**Comment by kyleam** [comment]
> It seems your function only finds files called `Snakefile`, right? So
> no matter what I set the dir functions to it would not work in my
> case.

Yes. I was just pointing you to information on how it currently at the
moment, not saying that your setup is currently supported.

> My original graph functions just took the absolute path of the file
> visited by the buffer, which is what I would want in 100% of
> cases.

My understanding is that that would only work when the target is in
the same directory as \<name>.snakefile (which isn't the case in the
example call to snakemake you gave).  For example, you mentioned that
a typical call to snakemake for you might look like this:

    ~/toplevel/ $ snakemake -s subdir/test.snakefile

So the targets are relative to ~/toplevel, not ~/toplevel/subdir.
However, your graph call would have been constructed as

    ~/toplevel/subdir/ $ snakemake -s /path/to/toplevel/subdir/test.snakefile --dag

which should fail because the targets can be resolved when snakemake
is called in ~/toplevel, but not when it's called in
~/toplevel/subdir/.  Testing out your `snakemake-show-dag` command
from #9 seems to confirm this.

Am I missing something?

> Perhaps you (or I) could add some similar capability with an
> interactive function
> (`snakemake-create-dag(/rulegraph)-for-this-file`)?

Yes, that's one option.  For the reasons I gave above, I think that
works only if the intention is to call snakemake from the current
directory.  I'm also considering making the popup support the
`--snakefile` flag, which could probably then make the extra functions
unnecessary if this is automatically set when called from a Snakemake
mode buffer.

But this still has the issue of how to determine which directory
snakemake should be called from.  With the current system, the
presence of a Snakefile is used to reliably determine this, but once
the `--snakefile` argument is introduced into the equation, it's not
as clear where snakemake should be called from.

Can you explain a bit more your motivation for having lots of separate
\*.snakefile's instead of a single Snakefile for the project?  I had
assumed that people generally go with the default name, Snakefile,
and, if there are rules in other \*.snakefile/\*.smrules files, these
are injected into the main Snakefile via `include: ...`.  But perhaps
heavy use of the `--snakefile` argument is common practice.

**Comment by endrebak** [comment]
I am working on my PhD which requires plenty of different analyses. I collect the related analyses into different snakefiles in the same folders. My main reason for not having them in the same file is to keep the files small and easier to edit, understand and reason about. 

Perhaps your setup would work if I created new folders for each snakefile, so that `a/b.snakefile` becomes `a/b/Snakefile`.

I guess you could ping https://github.com/johanneskoester and ask about his opinion.

**Comment by kyleam** [comment]
Thought about this a bit more, but I still don't see a clear way to
deal with the `--snakefile` option.  Given that you don't have any
interest in building targets from within Emacs, I've gone with your
suggestion and have created a `snakemake-graph-this-file` command
(efbfad4).  It deals with the uncertainty of what directory to call
Snakemake from by optionally prompting the user for the directory.
Please let me know how that works for you.
