### ISSUE TITLE
make error at installation

### ISSUE THREAD

**Issue by jvanheld** [kyleam/snakemake-mode#3]
Hi,
I downloaded a clone from snakemake-mode, and attempted to install it on Mac OS X Yosemite.
When I run "make" in the "snakemake-mode" driectory, I get the following error message. 

Would you have any idea about how to fix it?

Thanks

Jacques

Wrong number of arguments: #[(file &optional save-after) "!??	\"?	ɉ?O?	)?!?
                                                                                    ?&
                                                                                      q??(???)??*\"\"!!q??+)? ?V?I??,\"??,!?V??,\"???~?eb?
                                                                                                                                          ??????ɔ?.8?!8/01
             ???
?.8???ɔb??)?]   !??0<??0G?U???0/\"??t???\"?????2!?1`|??+??
             ???db?????#?
                         ?=??!*3?? ?? ?
-?" [file name no-autoloads existing-buffer found load-name file-name-nondirectory string-match "\\.elc?\\(\\.\\|$\\)" 0 ...] 7 ("/usr/share/emacs/22.1/lisp/emacs-lisp/autoload.elc" . 9347) "fUpdate autoloads for file: 
p"], 3
make: *** [snakemake-mode-autoloads.el] Error 255

**Comment by kyleam** [comment]
It seems like `update-file-autoloads` in Emacs 22.1 doesn't accept a third argument.  I've just pushed a change (295bbfbc94727691d7e9919abf9f358ab7a6b241) that might fix it.  But you don't need the autoloads file (or to run `make` at all) to use Snakemake mode.  You can just put it in your load-path and add `(require 'snakemake-mode)` somewhere in your startup files.

However, because Snakemake mode depends on the new python.el, it'll only work properly on Emacs version 24 and later.

**Comment by kyleam** [comment]
Please reopen if you still run into problems with Emacs 24.
